version: '3.8'
services:
  todofront:
    depends_on:
      - todoback
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_HOST: todoback
      
  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001
      
  todotests:
    depends_on:
      - todofront
      - todoback
    image: todotests
    restart: always
    environment:
      FRONT_HOST: todofront
